export { getPatientOverviewController } from "./controller/doctor/overview/pateint.controller";
export { deleteProfileController } from "./controller/delete.profile.controller";
export { workHoursController } from "./controller/doctor/settings/work.hours.controller";
export { deleteMedicalHistoryController } from "./controller/patient/delete.medical_history.controller";
export { editMedicalHistoryController } from "./controller/patient/edit.medical_history.controller";
export { getMedicalDataController } from "./controller/patient/get.medical_history.controller";
export { editProfileController } from "./controller/edite.profile.controller";
export { createNewMedicalHistoryController } from "./controller/patient/create.medical_history.controller";
export { profileController } from "./controller/profile.controller";
