export interface IRegion {
  readonly id: number
  readonly number: number
  readonly governorate_number: number
  readonly city_name_ar: string
  readonly city_name_en: string
}

export const cityData: IRegion[] = [
  // القاهرة
  { 'id': 1, 'number': 1, 'governorate_number': 1, 'city_name_ar': '15 مايو', 'city_name_en': '15 May' },
  { 'id': 2, 'number': 2, 'governorate_number': 1, 'city_name_ar': 'الازبكية', 'city_name_en': 'Al Azbakeyah' },
  { 'id': 3, 'number': 3, 'governorate_number': 1, 'city_name_ar': 'البساتين', 'city_name_en': 'Al Basatin' },
  { 'id': 4, 'number': 4, 'governorate_number': 1, 'city_name_ar': 'التبين', 'city_name_en': 'Tebin' },
  { 'id': 5, 'number': 5, 'governorate_number': 1, 'city_name_ar': 'الخليفة', 'city_name_en': 'El-Khalifa' },
  { 'id': 6, 'number': 6, 'governorate_number': 1, 'city_name_ar': 'الدراسة', 'city_name_en': 'El darrasa' },
  { 'id': 7, 'number': 7, 'governorate_number': 1, 'city_name_ar': 'الدرب الاحمر', 'city_name_en': 'Aldarb Alahmar' },
  { 'id': 8, 'number': 8, 'governorate_number': 1, 'city_name_ar': 'الزاوية الحمراء', 'city_name_en': 'Zawya al-Hamra' },
  { 'id': 9, 'number': 9, 'governorate_number': 1, 'city_name_ar': 'الزيتون', 'city_name_en': 'El-Zaytoun' },
  { 'id': 10, 'number': 10, 'governorate_number': 1, 'city_name_ar': 'الساحل', 'city_name_en': 'Sahel' },
  { 'id': 11, 'number': 11, 'governorate_number': 1, 'city_name_ar': 'السلام', 'city_name_en': 'El Salam' },
  { 'id': 12, 'number': 12, 'governorate_number': 1, 'city_name_ar': 'السيدة زينب', 'city_name_en': 'Sayeda Zeinab' },
  { 'id': 13, 'number': 13, 'governorate_number': 1, 'city_name_ar': 'الشرابية', 'city_name_en': 'El Sharabeya' },
  { 'id': 14, 'number': 14, 'governorate_number': 1, 'city_name_ar': 'مدينة الشروق', 'city_name_en': 'Shorouk' },
  { 'id': 15, 'number': 15, 'governorate_number': 1, 'city_name_ar': 'الظاهر', 'city_name_en': 'El Daher' },
  { 'id': 16, 'number': 16, 'governorate_number': 1, 'city_name_ar': 'العتبة', 'city_name_en': 'Ataba' },
  { 'id': 17, 'number': 17, 'governorate_number': 1, 'city_name_ar': 'القاهرة الجديدة', 'city_name_en': 'New Cairo' },
  { 'id': 18, 'number': 18, 'governorate_number': 1, 'city_name_ar': 'التجمع الاول', 'city_name_en': '1st Settlement' },
  { 'id': 19, 'number': 19, 'governorate_number': 1, 'city_name_ar': 'التجمع الثاني', 'city_name_en': '2nd Settlement' },
  { 'id': 20, 'number': 20, 'governorate_number': 1, 'city_name_ar': 'التجمع الثالث', 'city_name_en': '3rd Settlement' },
  { 'id': 21, 'number': 21, 'governorate_number': 1, 'city_name_ar': 'التجمع الرابع', 'city_name_en': '4th Settlement' },
  { 'id': 22, 'number': 22, 'governorate_number': 1, 'city_name_ar': 'التجمع الخامس', 'city_name_en': '5th Settlement' },
  { 'id': 23, 'number': 23, 'governorate_number': 1, 'city_name_ar': 'التجمع السادس', 'city_name_en': '6th Settlement' },
  { 'id': 24, 'number': 24, 'governorate_number': 1, 'city_name_ar': 'المرج', 'city_name_en': 'El Marg' },
  { 'id': 25, 'number': 25, 'governorate_number': 1, 'city_name_ar': 'عزبة النخل', 'city_name_en': 'Ezbet el Nakhl' },
  { 'id': 26, 'number': 26, 'governorate_number': 1, 'city_name_ar': 'المطرية', 'city_name_en': 'Matareya' },
  { 'id': 27, 'number': 27, 'governorate_number': 1, 'city_name_ar': 'المعادى', 'city_name_en': 'Maadi' },
  { 'id': 28, 'number': 28, 'governorate_number': 1, 'city_name_ar': 'المعصرة', 'city_name_en': 'Maasara' },
  { 'id': 29, 'number': 29, 'governorate_number': 1, 'city_name_ar': 'المقطم', 'city_name_en': 'Mokattam' },
  { 'id': 30, 'number': 30, 'governorate_number': 1, 'city_name_ar': 'المنيل', 'city_name_en': 'Manyal' },
  { 'id': 31, 'number': 31, 'governorate_number': 1, 'city_name_ar': 'الموسكى', 'city_name_en': 'Mosky' },
  { 'id': 32, 'number': 32, 'governorate_number': 1, 'city_name_ar': 'النزهة', 'city_name_en': 'Nozha' },
  { 'id': 33, 'number': 33, 'governorate_number': 1, 'city_name_ar': 'الوايلى', 'city_name_en': 'Waily' },
  { 'id': 34, 'number': 34, 'governorate_number': 1, 'city_name_ar': 'باب الشعرية', 'city_name_en': 'Bab al-Shereia' },
  { 'id': 35, 'number': 35, 'governorate_number': 1, 'city_name_ar': 'بولاق', 'city_name_en': 'Bolaq' },
  { 'id': 36, 'number': 36, 'governorate_number': 1, 'city_name_ar': 'جاردن سيتى', 'city_name_en': 'Garden City' },
  { 'id': 37, 'number': 37, 'governorate_number': 1, 'city_name_ar': 'حدائق القبة', 'city_name_en': 'Hadayek El-Kobba' },
  { 'id': 38, 'number': 38, 'governorate_number': 1, 'city_name_ar': 'حلوان', 'city_name_en': 'Helwan' },
  { 'id': 39, 'number': 39, 'governorate_number': 1, 'city_name_ar': 'دار السلام', 'city_name_en': 'Dar Al Salam' },
  { 'id': 40, 'number': 40, 'governorate_number': 1, 'city_name_ar': 'شبرا', 'city_name_en': 'Shubra' },
  { 'id': 41, 'number': 41, 'governorate_number': 1, 'city_name_ar': 'طره', 'city_name_en': 'Tura' },
  { 'id': 42, 'number': 42, 'governorate_number': 1, 'city_name_ar': 'عابدين', 'city_name_en': 'Abdeen' },
  { 'id': 43, 'number': 43, 'governorate_number': 1, 'city_name_ar': 'عباسية', 'city_name_en': 'Abaseya' },
  { 'id': 44, 'number': 44, 'governorate_number': 1, 'city_name_ar': 'عين شمس', 'city_name_en': 'Ain Shams' },
  { 'id': 45, 'number': 45, 'governorate_number': 1, 'city_name_ar': 'مدينة نصر', 'city_name_en': 'Nasr City' },
  { 'id': 46, 'number': 46, 'governorate_number': 1, 'city_name_ar': 'مصر الجديدة', 'city_name_en': 'Heliopolis' },
  { 'id': 47, 'number': 47, 'governorate_number': 1, 'city_name_ar': 'مصر القديمة', 'city_name_en': 'Masr Al Qadima' },
  { 'id': 48, 'number': 48, 'governorate_number': 1, 'city_name_ar': 'منشية ناصر', 'city_name_en': 'Mansheya Nasir' },
  { 'id': 49, 'number': 49, 'governorate_number': 1, 'city_name_ar': 'مدينة بدر', 'city_name_en': 'Badr City' },
  { 'id': 50, 'number': 50, 'governorate_number': 1, 'city_name_ar': 'وسط البلد', 'city_name_en': 'Cairo Downtown' },
  { 'id': 51, 'number': 51, 'governorate_number': 1, 'city_name_ar': 'الزمالك', 'city_name_en': 'Zamalek' },
  { 'id': 52, 'number': 52, 'governorate_number': 1, 'city_name_ar': 'قصر النيل', 'city_name_en': 'Kasr El Nile' },
  { 'id': 53, 'number': 53, 'governorate_number': 1, 'city_name_ar': 'الرحاب', 'city_name_en': 'Rehab' },
  { 'id': 54, 'number': 54, 'governorate_number': 1, 'city_name_ar': 'القطامية', 'city_name_en': 'Katameya' },
  { 'id': 55, 'number': 55, 'governorate_number': 1, 'city_name_ar': 'مدينتي', 'city_name_en': 'Madinty' },
  { 'id': 56, 'number': 56, 'governorate_number': 1, 'city_name_ar': 'روض الفرج', 'city_name_en': 'Rod Alfarag' },
  { 'id': 57, 'number': 57, 'governorate_number': 1, 'city_name_ar': 'شيراتون', 'city_name_en': 'Sheraton' },
  { 'id': 58, 'number': 58, 'governorate_number': 1, 'city_name_ar': 'الجمالية', 'city_name_en': 'El-Gamaleya' },
  { 'id': 59, 'number': 59, 'governorate_number': 20, 'city_name_ar': 'العاشر من رمضان', 'city_name_en': '10th of Ramadan City' },
  { 'id': 60, 'number': 60, 'governorate_number': 1, 'city_name_ar': 'الحلمية', 'city_name_en': 'Helmeyat Alzaytoun' },
  { 'id': 61, 'number': 61, 'governorate_number': 1, 'city_name_ar': 'النزهة الجديدة', 'city_name_en': 'New Nozha' },
  { 'id': 62, 'number': 62, 'governorate_number': 1, 'city_name_ar': 'العاصمة الإدارية', 'city_name_en': 'Capital New' },
  { 'id': 63, 'number': 63, 'governorate_number': 1, 'city_name_ar': 'زهراء المعادي', 'city_name_en': 'Zahraa El Maadi' },
  { 'id': 64, 'number': 64, 'governorate_number': 1, 'city_name_ar': 'هيليوبوليس الجديدة', 'city_name_en': 'New Heliopolis' },
  { 'id': 65, 'number': 65, 'governorate_number': 1, 'city_name_ar': 'زهراء مدينة نصر', 'city_name_en': 'Zahraa Nasr City' },
  ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// الجيزة
  { 'id': 66, 'number': 66, 'governorate_number': 2, 'city_name_ar': 'ميدان الجيزة', 'city_name_en': 'Giza Square' },
  { 'id': 67, 'number': 67, 'governorate_number': 2, 'city_name_ar': 'الشيخ زايد', 'city_name_en': 'Cheikh Zayed' },
  { 'id': 68, 'number': 68, 'governorate_number': 2, 'city_name_ar': 'الحوامدية', 'city_name_en': 'Hawamdiyah' },
  { 'id': 69, 'number': 69, 'governorate_number': 2, 'city_name_ar': 'البدرشين', 'city_name_en': 'Al Badrasheen' },
  { 'id': 70, 'number': 70, 'governorate_number': 2, 'city_name_ar': 'الصف', 'city_name_en': 'Saf' },
  { 'id': 71, 'number': 71, 'governorate_number': 2, 'city_name_ar': 'أطفيح', 'city_name_en': 'Atfih' },
  { 'id': 72, 'number': 72, 'governorate_number': 2, 'city_name_ar': 'العياط', 'city_name_en': 'Al Ayat' },
  { 'id': 73, 'number': 73, 'governorate_number': 2, 'city_name_ar': 'الباويطي', 'city_name_en': 'Al-Bawaiti' },
  { 'id': 74, 'number': 74, 'governorate_number': 2, 'city_name_ar': 'منشأة القناطر', 'city_name_en': 'ManshiyetAl Qanater' },
  { 'id': 75, 'number': 75, 'governorate_number': 2, 'city_name_ar': 'أوسيم', 'city_name_en': 'Oaseem' },
  { 'id': 76, 'number': 76, 'governorate_number': 2, 'city_name_ar': 'كرداسة', 'city_name_en': 'Kerdasa' },
  { 'id': 77, 'number': 77, 'governorate_number': 2, 'city_name_ar': 'أبو النمرس', 'city_name_en': 'Abu Nomros' },
  { 'id': 78, 'number': 78, 'governorate_number': 2, 'city_name_ar': 'كفر غطاطي', 'city_name_en': 'Kafr Ghati' },
  { 'id': 79, 'number': 79, 'governorate_number': 2, 'city_name_ar': 'منشأة البكاري', 'city_name_en': 'Manshiyet Al Bakari' },
  { 'id': 80, 'number': 80, 'governorate_number': 2, 'city_name_ar': 'الدقى', 'city_name_en': 'Dokki' },
  { 'id': 81, 'number': 81, 'governorate_number': 2, 'city_name_ar': 'العجوزة', 'city_name_en': 'Agouza' },
  { 'id': 82, 'number': 82, 'governorate_number': 2, 'city_name_ar': 'الهرم', 'city_name_en': 'Haram' },
  { 'id': 83, 'number': 83, 'governorate_number': 2, 'city_name_ar': 'الوراق', 'city_name_en': 'Warraq' },
  { 'id': 84, 'number': 84, 'governorate_number': 2, 'city_name_ar': 'امبابة', 'city_name_en': 'Imbaba' },
  { 'id': 85, 'number': 85, 'governorate_number': 2, 'city_name_ar': 'بولاق الدكرور', 'city_name_en': 'Boulaq Dakrour' },
  { 'id': 86, 'number': 86, 'governorate_number': 2, 'city_name_ar': 'الواحات البحرية', 'city_name_en': 'Al Wahat Al Baharia' },
  { 'id': 87, 'number': 87, 'governorate_number': 2, 'city_name_ar': 'العمرانية', 'city_name_en': 'Omraneya' },
  { 'id': 88, 'number': 88, 'governorate_number': 2, 'city_name_ar': 'المنيب', 'city_name_en': 'Moneeb' },
  { 'id': 89, 'number': 89, 'governorate_number': 2, 'city_name_ar': 'بين السرايات', 'city_name_en': 'Bin Alsarayat' },
  { 'id': 90, 'number': 90, 'governorate_number': 2, 'city_name_ar': 'الكيت كات', 'city_name_en': 'Kit Kat' },
  { 'id': 91, 'number': 91, 'governorate_number': 2, 'city_name_ar': 'المهندسين', 'city_name_en': 'Mohandessin' },
  { 'id': 92, 'number': 92, 'governorate_number': 2, 'city_name_ar': 'فيصل', 'city_name_en': 'Faisal' },
  { 'id': 93, 'number': 93, 'governorate_number': 2, 'city_name_ar': 'أبو رواش', 'city_name_en': 'Abu Rawash' },
  { 'id': 94, 'number': 94, 'governorate_number': 2, 'city_name_ar': 'حدائق الأهرام', 'city_name_en': 'Hadayek Alahram' },
  { 'id': 95, 'number': 95, 'governorate_number': 2, 'city_name_ar': 'الحرانية', 'city_name_en': 'Haraneya' },
  { 'id': 96, 'number': 96, 'governorate_number': 2, 'city_name_ar': 'حدائق اكتوبر', 'city_name_en': 'Hadayek October' },
  { 'id': 97, 'number': 97, 'governorate_number': 2, 'city_name_ar': 'صفط اللبن', 'city_name_en': 'Saft Allaban' },
  { 'id': 98, 'number': 98, 'governorate_number': 2, 'city_name_ar': 'القرية الذكية', 'city_name_en': 'Smart Village' },
  { 'id': 99, 'number': 99, 'governorate_number': 2, 'city_name_ar': 'ارض اللواء', 'city_name_en': 'Ard Ellwaa' },
  { 'id': 100, 'number': 100, 'governorate_number': 2, 'city_name_ar': '6 اكتوبر', 'city_name_en': 'October 6' },
  ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// الأسكندرية
  { 'id': 101, 'number': 101, 'governorate_number': 3, 'city_name_ar': 'ابو قير', 'city_name_en': 'Abu Qir' },
  { 'id': 102, 'number': 102, 'governorate_number': 3, 'city_name_ar': 'الابراهيمية', 'city_name_en': 'Al Ibrahimeyah' },
  { 'id': 103, 'number': 103, 'governorate_number': 3, 'city_name_ar': 'الأزاريطة', 'city_name_en': 'Azarita' },
  { 'id': 104, 'number': 104, 'governorate_number': 3, 'city_name_ar': 'الانفوشى', 'city_name_en': 'Anfoushi' },
  { 'id': 105, 'number': 105, 'governorate_number': 3, 'city_name_ar': 'الدخيلة', 'city_name_en': 'Dekheila' },
  { 'id': 106, 'number': 106, 'governorate_number': 3, 'city_name_ar': 'السيوف', 'city_name_en': 'El Soyof' },
  { 'id': 107, 'number': 107, 'governorate_number': 3, 'city_name_ar': 'العامرية', 'city_name_en': 'Ameria' },
  { 'id': 108, 'number': 108, 'governorate_number': 3, 'city_name_ar': 'اللبان', 'city_name_en': 'El Labban' },
  { 'id': 109, 'number': 109, 'governorate_number': 3, 'city_name_ar': 'المفروزة', 'city_name_en': 'Al Mafrouza' },
  { 'id': 110, 'number': 110, 'governorate_number': 3, 'city_name_ar': 'المنتزه', 'city_name_en': 'El Montaza' },
  { 'id': 111, 'number': 111, 'governorate_number': 3, 'city_name_ar': 'المنشية', 'city_name_en': 'Mansheya' },
  { 'id': 112, 'number': 112, 'governorate_number': 3, 'city_name_ar': 'قسم المنشية', 'city_name_en': 'Mansheya Department' },
  { 'id': 113, 'number': 113, 'governorate_number': 3, 'city_name_ar': 'الناصرية', 'city_name_en': 'Naseria' },
  { 'id': 114, 'number': 114, 'governorate_number': 3, 'city_name_ar': 'امبروزو', 'city_name_en': 'Ambrozo' },
  { 'id': 115, 'number': 115, 'governorate_number': 3, 'city_name_ar': 'باب شرق', 'city_name_en': 'Bab Sharq' },
  { 'id': 116, 'number': 116, 'governorate_number': 3, 'city_name_ar': 'برج العرب', 'city_name_en': 'Bourj Alarab' },
  { 'id': 117, 'number': 117, 'governorate_number': 3, 'city_name_ar': 'ستانلى', 'city_name_en': 'Stanley' },
  { 'id': 118, 'number': 118, 'governorate_number': 3, 'city_name_ar': 'سموحة', 'city_name_en': 'Smouha' },
  { 'id': 119, 'number': 119, 'governorate_number': 3, 'city_name_ar': 'سيدى بشر', 'city_name_en': 'Snumberi Bishr' },
  { 'id': 120, 'number': 120, 'governorate_number': 3, 'city_name_ar': 'شدس', 'city_name_en': 'Shads' },
  { 'id': 121, 'number': 121, 'governorate_number': 3, 'city_name_ar': 'الهانوفيل', 'city_name_en': 'Al Hanouvel' },
  { 'id': 122, 'number': 122, 'governorate_number': 3, 'city_name_ar': 'غيط العنب', 'city_name_en': 'Gheet Alenab' },
  { 'id': 123, 'number': 123, 'governorate_number': 3, 'city_name_ar': 'فلمينج', 'city_name_en': 'Fleming' },
  { 'id': 124, 'number': 124, 'governorate_number': 3, 'city_name_ar': 'فيكتوريا', 'city_name_en': 'Victoria' },
  { 'id': 125, 'number': 125, 'governorate_number': 3, 'city_name_ar': 'كامب شيزار', 'city_name_en': 'Camp Shizar' },
  { 'id': 126, 'number': 126, 'governorate_number': 3, 'city_name_ar': 'كرموز', 'city_name_en': 'Karmooz' },
  { 'id': 127, 'number': 127, 'governorate_number': 3, 'city_name_ar': 'محطة الرمل', 'city_name_en': 'Mahta Alraml' },
  { 'id': 128, 'number': 128, 'governorate_number': 3, 'city_name_ar': 'مينا البصل', 'city_name_en': 'Mina El-Basal' },
  { 'id': 129, 'number': 129, 'governorate_number': 3, 'city_name_ar': 'العصافرة', 'city_name_en': 'Asafra' },
  { 'id': 130, 'number': 130, 'governorate_number': 3, 'city_name_ar': 'العجمي', 'city_name_en': 'Agamy' },
  { 'id': 131, 'number': 131, 'governorate_number': 3, 'city_name_ar': 'بكوس', 'city_name_en': 'Bakos' },
  { 'id': 132, 'number': 132, 'governorate_number': 3, 'city_name_ar': 'بولكلي', 'city_name_en': 'Boulkly' },
  { 'id': 133, 'number': 133, 'governorate_number': 3, 'city_name_ar': 'كليوباترا', 'city_name_en': 'Cleopatra' },
  { 'id': 134, 'number': 134, 'governorate_number': 3, 'city_name_ar': 'جليم', 'city_name_en': 'Glim' },
  { 'id': 135, 'number': 135, 'governorate_number': 3, 'city_name_ar': 'المعمورة', 'city_name_en': 'Al Mamurah' },
  { 'id': 136, 'number': 136, 'governorate_number': 3, 'city_name_ar': 'المندرة', 'city_name_en': 'Al Mandara' },
  { 'id': 137, 'number': 137, 'governorate_number': 3, 'city_name_ar': 'محرم بك', 'city_name_en': 'Moharam Bek' },
  { 'id': 138, 'number': 138, 'governorate_number': 3, 'city_name_ar': 'الشاطبي', 'city_name_en': 'Elshatby' },
  { 'id': 139, 'number': 139, 'governorate_number': 3, 'city_name_ar': 'سيدي جابر', 'city_name_en': 'Snumberi Gaber' },
  { 'id': 140, 'number': 140, 'governorate_number': 3, 'city_name_ar': 'الساحل الشمالي', 'city_name_en': 'North Coast' },
  { 'id': 141, 'number': 141, 'governorate_number': 3, 'city_name_ar': 'الحضرة', 'city_name_en': 'Alhadra' },
  { 'id': 142, 'number': 142, 'governorate_number': 3, 'city_name_ar': 'العطارين', 'city_name_en': 'Alattarin' },
  { 'id': 143, 'number': 143, 'governorate_number': 3, 'city_name_ar': 'سيدي كرير', 'city_name_en': 'Snumberi Kerir' },
  { 'id': 144, 'number': 144, 'governorate_number': 3, 'city_name_ar': 'الجمرك', 'city_name_en': 'Elgomrok' },
  { 'id': 145, 'number': 145, 'governorate_number': 3, 'city_name_ar': 'المكس', 'city_name_en': 'Al Max' },
  { 'id': 146, 'number': 146, 'governorate_number': 3, 'city_name_ar': 'مارينا', 'city_name_en': 'Marina' },
  { 'id': 147, 'number': 147, 'governorate_number': 3, 'city_name_ar': 'قسم مارينا العلمين السياحي', 'city_name_en': 'Marina El Alamein Tourism Section' },
  { 'id': 148, 'number': 148, 'governorate_number': 3, 'city_name_ar': 'لوران', 'city_name_en': 'Laurent' },
  { 'id': 149, 'number': 149, 'governorate_number': 3, 'city_name_ar': 'ميامي', 'city_name_en': 'Miami' },
  { 'id': 150, 'number': 150, 'governorate_number': 3, 'city_name_ar': 'ميامي الجديدة', 'city_name_en': 'New Miami' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  الدقهلية  
  { 'id': 151, 'number': 151, 'governorate_number': 4, 'city_name_ar': 'المنصورة', 'city_name_en': 'Mansoura' },
  { 'id': 152, 'number': 152, 'governorate_number': 4, 'city_name_ar': 'طلخا', 'city_name_en': 'Talkha' },
  { 'id': 153, 'number': 153, 'governorate_number': 4, 'city_name_ar': 'ميت غمر', 'city_name_en': 'Mitt Ghamr' },
  { 'id': 154, 'number': 154, 'governorate_number': 4, 'city_name_ar': 'دكرنس', 'city_name_en': 'Dekernes' },
  { 'id': 155, 'number': 155, 'governorate_number': 4, 'city_name_ar': 'أجا', 'city_name_en': 'Aga' },
  { 'id': 156, 'number': 156, 'governorate_number': 4, 'city_name_ar': 'منية النصر', 'city_name_en': 'Menia El Nasr' },
  { 'id': 157, 'number': 157, 'governorate_number': 4, 'city_name_ar': 'السنبلاوين', 'city_name_en': 'Sinbillawin' },
  { 'id': 158, 'number': 158, 'governorate_number': 4, 'city_name_ar': 'الكردي', 'city_name_en': 'El Kurdi' },
  { 'id': 159, 'number': 159, 'governorate_number': 4, 'city_name_ar': 'بني عبيد', 'city_name_en': 'Bani Ubanumber' },
  { 'id': 160, 'number': 160, 'governorate_number': 4, 'city_name_ar': 'المنزلة', 'city_name_en': 'Al Manzala' },
  { 'id': 161, 'number': 161, 'governorate_number': 4, 'city_name_ar': 'تمي الأمديد', 'city_name_en': 'tami al\'amdnumber' },
  { 'id': 162, 'number': 162, 'governorate_number': 4, 'city_name_ar': 'الجمالية', 'city_name_en': 'aljamalia' },
  { 'id': 163, 'number': 163, 'governorate_number': 4, 'city_name_ar': 'شربين', 'city_name_en': 'Sherbin' },
  { 'id': 164, 'number': 164, 'governorate_number': 4, 'city_name_ar': 'المطرية', 'city_name_en': 'Mataria' },
  { 'id': 165, 'number': 165, 'governorate_number': 4, 'city_name_ar': 'بلقاس', 'city_name_en': 'Belqas' },
  { 'id': 166, 'number': 166, 'governorate_number': 4, 'city_name_ar': 'ميت سلسيل', 'city_name_en': 'Meet Salsil' },
  { 'id': 167, 'number': 167, 'governorate_number': 4, 'city_name_ar': 'جمصة', 'city_name_en': 'Gamasa' },
  { 'id': 168, 'number': 168, 'governorate_number': 4, 'city_name_ar': 'محلة دمنة', 'city_name_en': 'Mahalat Damana' },
  { 'id': 169, 'number': 169, 'governorate_number': 4, 'city_name_ar': 'نبروه', 'city_name_en': 'Nabroh' },
  ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// البحر الأحمر
  { 'id': 170, 'number': 170, 'governorate_number': 5, 'city_name_ar': 'الغردقة', 'city_name_en': 'Hurghada' },
  { 'id': 171, 'number': 171, 'governorate_number': 5, 'city_name_ar': 'رأس غارب', 'city_name_en': 'Ras Ghareb' },
  { 'id': 172, 'number': 172, 'governorate_number': 5, 'city_name_ar': 'سفاجا', 'city_name_en': 'Safaga' },
  { 'id': 173, 'number': 173, 'governorate_number': 5, 'city_name_ar': 'القصير', 'city_name_en': 'El Qusiar' },
  { 'id': 174, 'number': 174, 'governorate_number': 5, 'city_name_ar': 'مرسى علم', 'city_name_en': 'Marsa Alam' },
  { 'id': 175, 'number': 175, 'governorate_number': 5, 'city_name_ar': 'الشلاتين', 'city_name_en': 'Shalatin' },
  { 'id': 176, 'number': 176, 'governorate_number': 5, 'city_name_ar': 'حلايب', 'city_name_en': 'Halaib' },
  { 'id': 177, 'number': 177, 'governorate_number': 5, 'city_name_ar': 'الدهار', 'city_name_en': 'Aldahar' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////البحيرة
  { 'id': 178, 'number': 178, 'governorate_number': 6, 'city_name_ar': 'دمنهور', 'city_name_en': 'Damanhour' },
  { 'id': 179, 'number': 179, 'governorate_number': 6, 'city_name_ar': 'كفر الدوار', 'city_name_en': 'Kafr El Dawar' },
  { 'id': 180, 'number': 180, 'governorate_number': 6, 'city_name_ar': 'رشيد', 'city_name_en': 'Rashnumber' },
  { 'id': 181, 'number': 181, 'governorate_number': 6, 'city_name_ar': 'إدكو', 'city_name_en': 'Edco' },
  { 'id': 182, 'number': 182, 'governorate_number': 6, 'city_name_ar': 'أبو المطامير', 'city_name_en': 'Abu al-Matamir' },
  { 'id': 183, 'number': 183, 'governorate_number': 6, 'city_name_ar': 'أبو حمص', 'city_name_en': 'Abu Homs' },
  { 'id': 184, 'number': 184, 'governorate_number': 6, 'city_name_ar': 'الدلنجات', 'city_name_en': 'Delengat' },
  { 'id': 185, 'number': 185, 'governorate_number': 6, 'city_name_ar': 'المحمودية', 'city_name_en': 'Mahmoudiyah' },
  { 'id': 186, 'number': 186, 'governorate_number': 6, 'city_name_ar': 'الرحمانية', 'city_name_en': 'Rahmaniyah' },
  { 'id': 187, 'number': 187, 'governorate_number': 6, 'city_name_ar': 'إيتاي البارود', 'city_name_en': 'Itai Baroud' },
  { 'id': 188, 'number': 188, 'governorate_number': 6, 'city_name_ar': 'حوش عيسى', 'city_name_en': 'Housh Eissa' },
  { 'id': 189, 'number': 189, 'governorate_number': 6, 'city_name_ar': 'شبراخيت', 'city_name_en': 'Shubrakhit' },
  { 'id': 190, 'number': 190, 'governorate_number': 6, 'city_name_ar': 'كوم حمادة', 'city_name_en': 'Kom Hamada' },
  { 'id': 191, 'number': 191, 'governorate_number': 6, 'city_name_ar': 'بدر', 'city_name_en': 'Badr' },
  { 'id': 192, 'number': 192, 'governorate_number': 6, 'city_name_ar': 'وادي النطرون', 'city_name_en': 'Wadi Natrun' },
  { 'id': 193, 'number': 193, 'governorate_number': 6, 'city_name_ar': 'النوبارية الجديدة', 'city_name_en': 'New Nubaria' },
  { 'id': 194, 'number': 194, 'governorate_number': 6, 'city_name_ar': 'النوبارية', 'city_name_en': 'Alnoubareya' },
  { 'id': 195, 'number': 195, 'governorate_number': 6, 'city_name_ar': 'مركز وادى النطرون', 'city_name_en': 'Wadi El-Natroun Center' },

  ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// الفيوم
  { 'id': 196, 'number': 196, 'governorate_number': 7, 'city_name_ar': 'الفيوم', 'city_name_en': 'Fayoum' },
  { 'id': 197, 'number': 197, 'governorate_number': 7, 'city_name_ar': 'الفيوم الجديدة', 'city_name_en': 'Fayoum El Gednumbera' },
  { 'id': 198, 'number': 198, 'governorate_number': 7, 'city_name_ar': 'طامية', 'city_name_en': 'Tamiya' },
  { 'id': 199, 'number': 199, 'governorate_number': 7, 'city_name_ar': 'سنورس', 'city_name_en': 'Snores' },
  { 'id': 200, 'number': 200, 'governorate_number': 7, 'city_name_ar': 'إطسا', 'city_name_en': 'Etsa' },
  { 'id': 201, 'number': 201, 'governorate_number': 7, 'city_name_ar': 'إبشواي', 'city_name_en': 'Epschway' },
  { 'id': 202, 'number': 202, 'governorate_number': 7, 'city_name_ar': 'يوسف الصديق', 'city_name_en': 'Yusuf El Sediaq' },
  { 'id': 203, 'number': 203, 'governorate_number': 7, 'city_name_ar': 'الحادقة', 'city_name_en': 'Hadqa' },
  { 'id': 204, 'number': 204, 'governorate_number': 7, 'city_name_ar': 'اطسا', 'city_name_en': 'Atsa' },
  { 'id': 205, 'number': 205, 'governorate_number': 7, 'city_name_ar': 'الجامعة', 'city_name_en': 'Algamaa' },
  { 'id': 206, 'number': 206, 'governorate_number': 7, 'city_name_ar': 'السيالة', 'city_name_en': 'Sayala' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////الغربية
  { 'id': 207, 'number': 207, 'governorate_number': 8, 'city_name_ar': 'طنطا', 'city_name_en': 'Tanta' },
  { 'id': 208, 'number': 208, 'governorate_number': 8, 'city_name_ar': 'المحلة الكبرى', 'city_name_en': 'Al Mahalla Al Kobra' },
  { 'id': 209, 'number': 209, 'governorate_number': 8, 'city_name_ar': 'كفر الزيات', 'city_name_en': 'Kafr El Zayat' },
  { 'id': 210, 'number': 210, 'governorate_number': 8, 'city_name_ar': 'زفتى', 'city_name_en': 'Zefta' },
  { 'id': 211, 'number': 211, 'governorate_number': 8, 'city_name_ar': 'السنطة', 'city_name_en': 'El Santa' },
  { 'id': 212, 'number': 212, 'governorate_number': 8, 'city_name_ar': 'قطور', 'city_name_en': 'Qutour' },
  { 'id': 213, 'number': 213, 'governorate_number': 8, 'city_name_ar': 'بسيون', 'city_name_en': 'Basion' },
  { 'id': 214, 'number': 214, 'governorate_number': 8, 'city_name_ar': 'سمنود', 'city_name_en': 'Samannoud' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////الإسماعلية
  { 'id': 215, 'number': 215, 'governorate_number': 9, 'city_name_ar': 'الإسماعيلية', 'city_name_en': 'Ismailia' },
  { 'id': 216, 'number': 216, 'governorate_number': 9, 'city_name_ar': 'فايد', 'city_name_en': 'Fayed' },
  { 'id': 217, 'number': 217, 'governorate_number': 9, 'city_name_ar': 'القنطرة شرق', 'city_name_en': 'Qantara Sharq' },
  { 'id': 218, 'number': 218, 'governorate_number': 9, 'city_name_ar': 'القنطرة غرب', 'city_name_en': 'Qantara Gharb' },
  { 'id': 219, 'number': 219, 'governorate_number': 9, 'city_name_ar': 'التل الكبير', 'city_name_en': 'El Tal El Kabier' },
  { 'id': 220, 'number': 220, 'governorate_number': 9, 'city_name_ar': 'أبو صوير', 'city_name_en': 'Abu Sawir' },
  { 'id': 221, 'number': 221, 'governorate_number': 9, 'city_name_ar': 'القصاصين الجديدة', 'city_name_en': 'Kasasien El Gednumbera' },
  { 'id': 222, 'number': 222, 'governorate_number': 9, 'city_name_ar': 'نفيشة', 'city_name_en': 'Nefesha' },
  { 'id': 223, 'number': 223, 'governorate_number': 9, 'city_name_ar': 'الشيخ زايد', 'city_name_en': 'Sheikh Zayed' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////المنوفية
  { 'id': 224, 'number': 224, 'governorate_number': 10, 'city_name_ar': 'شبين الكوم', 'city_name_en': 'Shbeen El Koom' },
  { 'id': 225, 'number': 225, 'governorate_number': 10, 'city_name_ar': 'مدينة السادات', 'city_name_en': 'Sadat City' },
  { 'id': 226, 'number': 226, 'governorate_number': 10, 'city_name_ar': 'منوف', 'city_name_en': 'Menouf' },
  { 'id': 227, 'number': 227, 'governorate_number': 10, 'city_name_ar': 'سرس الليان', 'city_name_en': 'Sars El-Layan' },
  { 'id': 227, 'number': 227, 'governorate_number': 10, 'city_name_ar': 'أشمون', 'city_name_en': 'Ashmon' },
  { 'id': 228, 'number': 228, 'governorate_number': 10, 'city_name_ar': 'الباجور', 'city_name_en': 'Al Bagor' },
  { 'id': 229, 'number': 229, 'governorate_number': 10, 'city_name_ar': 'قويسنا', 'city_name_en': 'Quesna' },
  { 'id': 230, 'number': 230, 'governorate_number': 10, 'city_name_ar': 'بركة السبع', 'city_name_en': 'Berkat El Saba' },
  { 'id': 231, 'number': 231, 'governorate_number': 10, 'city_name_ar': 'تلا', 'city_name_en': 'Tala' },
  { 'id': 232, 'number': 232, 'governorate_number': 10, 'city_name_ar': 'الشهداء', 'city_name_en': 'Al Shohada' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////المنيا
  { 'id': 233, 'number': 233, 'governorate_number': 11, 'city_name_ar': 'المنيا', 'city_name_en': 'Minya' },
  { 'id': 234, 'number': 234, 'governorate_number': 11, 'city_name_ar': 'المنيا الجديدة', 'city_name_en': 'Minya El Gednumbera' },
  { 'id': 235, 'number': 235, 'governorate_number': 11, 'city_name_ar': 'العدوة', 'city_name_en': 'El Adwa' },
  { 'id': 236, 'number': 236, 'governorate_number': 11, 'city_name_ar': 'مغاغة', 'city_name_en': 'Magagha' },
  { 'id': 237, 'number': 237, 'governorate_number': 11, 'city_name_ar': 'بني مزار', 'city_name_en': 'Bani Mazar' },
  { 'id': 238, 'number': 238, 'governorate_number': 11, 'city_name_ar': 'مطاي', 'city_name_en': 'Mattay' },
  { 'id': 239, 'number': 239, 'governorate_number': 11, 'city_name_ar': 'سمالوط', 'city_name_en': 'Samalut' },
  { 'id': 240, 'number': 240, 'governorate_number': 11, 'city_name_ar': 'المدينة الفكرية', 'city_name_en': 'Madinat El Fekria' },
  { 'id': 241, 'number': 241, 'governorate_number': 11, 'city_name_ar': 'ملوي', 'city_name_en': 'Meloy' },
  { 'id': 242, 'number': 242, 'governorate_number': 11, 'city_name_ar': 'دير مواس', 'city_name_en': 'Deir Mawas' },
  { 'id': 243, 'number': 243, 'governorate_number': 11, 'city_name_ar': 'ابو قرقاص', 'city_name_en': 'Abu Qurqas' },
  { 'id': 244, 'number': 244, 'governorate_number': 11, 'city_name_ar': 'ارض سلطان', 'city_name_en': 'Ard Sultan' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////القليوبية
  { 'id': 245, 'number': 245, 'governorate_number': 12, 'city_name_ar': 'بنها', 'city_name_en': 'Banha' },
  { 'id': 246, 'number': 246, 'governorate_number': 12, 'city_name_ar': 'قليوب', 'city_name_en': 'Qalyub' },
  { 'id': 247, 'number': 247, 'governorate_number': 12, 'city_name_ar': 'شبرا الخيمة', 'city_name_en': 'Shubra Al Khaimah' },
  { 'id': 248, 'number': 248, 'governorate_number': 12, 'city_name_ar': 'القناطر الخيرية', 'city_name_en': 'Al Qanater Charity' },
  { 'id': 249, 'number': 249, 'governorate_number': 12, 'city_name_ar': 'الخانكة', 'city_name_en': 'Khanka' },
  { 'id': 250, 'number': 250, 'governorate_number': 12, 'city_name_ar': 'كفر شكر', 'city_name_en': 'Kafr Shukr' },
  { 'id': 251, 'number': 251, 'governorate_number': 12, 'city_name_ar': 'طوخ', 'city_name_en': 'Tukh' },
  { 'id': 252, 'number': 252, 'governorate_number': 12, 'city_name_ar': 'قها', 'city_name_en': 'Qaha' },
  { 'id': 253, 'number': 253, 'governorate_number': 12, 'city_name_ar': 'العبور', 'city_name_en': 'Obour' },
  { 'id': 254, 'number': 254, 'governorate_number': 12, 'city_name_ar': 'الخصوص', 'city_name_en': 'Khosous' },
  { 'id': 255, 'number': 255, 'governorate_number': 12, 'city_name_ar': 'شبين القناطر', 'city_name_en': 'Shibin Al Qanater' },
  { 'id': 256, 'number': 256, 'governorate_number': 12, 'city_name_ar': 'مسطرد', 'city_name_en': 'Mostorod' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////الوادي الجديد
  { 'id': 257, 'number': 257, 'governorate_number': 13, 'city_name_ar': 'الخارجة', 'city_name_en': 'El Kharga' },
  { 'id': 258, 'number': 258, 'governorate_number': 13, 'city_name_ar': 'باريس', 'city_name_en': 'Paris' },
  { 'id': 259, 'number': 259, 'governorate_number': 13, 'city_name_ar': 'موط', 'city_name_en': 'Mout' },
  { 'id': 260, 'number': 260, 'governorate_number': 13, 'city_name_ar': 'الفرافرة', 'city_name_en': 'Farafra' },
  { 'id': 261, 'number': 261, 'governorate_number': 13, 'city_name_ar': 'بلاط', 'city_name_en': 'Balat' },
  { 'id': 262, 'number': 262, 'governorate_number': 13, 'city_name_ar': 'الداخلة', 'city_name_en': 'Dakhla' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////السويس
  { 'id': 263, 'number': 263, 'governorate_number': 14, 'city_name_ar': 'السويس', 'city_name_en': 'Suez' },
  { 'id': 264, 'number': 264, 'governorate_number': 14, 'city_name_ar': 'الجناين', 'city_name_en': 'Alganayen' },
  { 'id': 265, 'number': 265, 'governorate_number': 14, 'city_name_ar': 'عتاقة', 'city_name_en': 'Ataqah' },
  { 'id': 266, 'number': 266, 'governorate_number': 14, 'city_name_ar': 'العين السخنة', 'city_name_en': 'Ain Sokhna' },
  { 'id': 267, 'number': 267, 'governorate_number': 14, 'city_name_ar': 'فيصل', 'city_name_en': 'Faysal' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////اسوان
  { 'id': 268, 'number': 268, 'governorate_number': 15, 'city_name_ar': 'أسوان', 'city_name_en': 'Aswan' },
  { 'id': 269, 'number': 269, 'governorate_number': 15, 'city_name_ar': 'أسوان الجديدة', 'city_name_en': 'Aswan El Gednumbera' },
  { 'id': 270, 'number': 270, 'governorate_number': 15, 'city_name_ar': 'دراو', 'city_name_en': 'Drau' },
  { 'id': 271, 'number': 271, 'governorate_number': 15, 'city_name_ar': 'كوم أمبو', 'city_name_en': 'Kom Ombo' },
  { 'id': 272, 'number': 272, 'governorate_number': 15, 'city_name_ar': 'نصر النوبة', 'city_name_en': 'Nasr Al Nuba' },
  { 'id': 273, 'number': 273, 'governorate_number': 15, 'city_name_ar': 'كلابشة', 'city_name_en': 'Kalabsha' },
  { 'id': 274, 'number': 274, 'governorate_number': 15, 'city_name_ar': 'إدفو', 'city_name_en': 'Edfu' },
  { 'id': 275, 'number': 275, 'governorate_number': 15, 'city_name_ar': 'الرديسية', 'city_name_en': 'Al-Radisiyah' },
  { 'id': 276, 'number': 276, 'governorate_number': 15, 'city_name_ar': 'البصيلية', 'city_name_en': 'Al Basilia' },
  { 'id': 277, 'number': 277, 'governorate_number': 15, 'city_name_ar': 'السباعية', 'city_name_en': 'Al Sibaeia' },
  { 'id': 278, 'number': 278, 'governorate_number': 15, 'city_name_ar': 'ابوسمبل السياحية', 'city_name_en': 'Abo Simbl Al Siyahia' },
  { 'id': 279, 'number': 279, 'governorate_number': 15, 'city_name_ar': 'مرسى علم', 'city_name_en': 'Marsa Alam' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////اسيوط
  { 'id': 280, 'number': 280, 'governorate_number': 16, 'city_name_ar': 'أسيوط', 'city_name_en': 'Assiut' },
  { 'id': 281, 'number': 281, 'governorate_number': 16, 'city_name_ar': 'أسيوط الجديدة', 'city_name_en': 'Assiut El Gednumbera' },
  { 'id': 282, 'number': 282, 'governorate_number': 16, 'city_name_ar': 'ديروط', 'city_name_en': 'Dayrout' },
  { 'id': 283, 'number': 283, 'governorate_number': 16, 'city_name_ar': 'منفلوط', 'city_name_en': 'Manfalut' },
  { 'id': 284, 'number': 284, 'governorate_number': 16, 'city_name_ar': 'القوصية', 'city_name_en': 'Qusiya' },
  { 'id': 285, 'number': 285, 'governorate_number': 16, 'city_name_ar': 'أبنوب', 'city_name_en': 'Abnoub' },
  { 'id': 286, 'number': 286, 'governorate_number': 16, 'city_name_ar': 'أبو تيج', 'city_name_en': 'Abu Tig' },
  { 'id': 287, 'number': 287, 'governorate_number': 16, 'city_name_ar': 'الغنايم', 'city_name_en': 'El Ghanaim' },
  { 'id': 288, 'number': 288, 'governorate_number': 16, 'city_name_ar': 'ساحل سليم', 'city_name_en': 'Sahel Selim' },
  { 'id': 289, 'number': 289, 'governorate_number': 16, 'city_name_ar': 'البداري', 'city_name_en': 'El Badari' },
  { 'id': 290, 'number': 290, 'governorate_number': 16, 'city_name_ar': 'صدفا', 'city_name_en': 'Snumberfa' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////بني سويف
  { 'id': 291, 'number': 291, 'governorate_number': 17, 'city_name_ar': 'بني سويف', 'city_name_en': 'Bani Sweif' },
  { 'id': 292, 'number': 292, 'governorate_number': 17, 'city_name_ar': 'بني سويف الجديدة', 'city_name_en': 'Beni Suef El Gednumbera' },
  { 'id': 293, 'number': 293, 'governorate_number': 17, 'city_name_ar': 'الواسطى', 'city_name_en': 'Al Wasta' },
  { 'id': 294, 'number': 294, 'governorate_number': 17, 'city_name_ar': 'ناصر', 'city_name_en': 'Naser' },
  { 'id': 295, 'number': 295, 'governorate_number': 17, 'city_name_ar': 'إهناسيا', 'city_name_en': 'Ehnasia' },
  { 'id': 296, 'number': 296, 'governorate_number': 17, 'city_name_ar': 'ببا', 'city_name_en': 'beba' },
  { 'id': 297, 'number': 297, 'governorate_number': 17, 'city_name_ar': 'الفشن', 'city_name_en': 'Fashn' },
  { 'id': 298, 'number': 298, 'governorate_number': 17, 'city_name_ar': 'سمسطا', 'city_name_en': 'Somasta' },
  { 'id': 299, 'number': 299, 'governorate_number': 17, 'city_name_ar': 'الاباصيرى', 'city_name_en': 'Alabbaseri' },
  { 'id': 300, 'number': 300, 'governorate_number': 17, 'city_name_ar': 'مقبل', 'city_name_en': 'Mokbel' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////بورسعيد
  { 'id': 301, 'number': 301, 'governorate_number': 18, 'city_name_ar': 'بورسعيد', 'city_name_en': 'Port Saead' },
  { 'id': 302, 'number': 302, 'governorate_number': 18, 'city_name_ar': 'بورفؤاد', 'city_name_en': 'Port Fouad' },
  { 'id': 303, 'number': 303, 'governorate_number': 18, 'city_name_ar': 'العرب', 'city_name_en': 'Alarab' },
  { 'id': 304, 'number': 304, 'governorate_number': 18, 'city_name_ar': 'حى الزهور', 'city_name_en': 'Zohour' },
  { 'id': 305, 'number': 305, 'governorate_number': 18, 'city_name_ar': 'حى الشرق', 'city_name_en': 'Alsharq' },
  { 'id': 306, 'number': 306, 'governorate_number': 18, 'city_name_ar': 'حى الضواحى', 'city_name_en': 'Aldawahi' },
  { 'id': 307, 'number': 307, 'governorate_number': 18, 'city_name_ar': 'حى المناخ', 'city_name_en': 'Almanakh' },
  { 'id': 308, 'number': 308, 'governorate_number': 18, 'city_name_ar': 'حى مبارك', 'city_name_en': 'Mubarak' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////دمياط
  { 'id': 309, 'number': 309, 'governorate_number': 19, 'city_name_ar': 'دمياط', 'city_name_en': 'Damietta' },
  { 'id': 310, 'number': 310, 'governorate_number': 19, 'city_name_ar': 'دمياط الجديدة', 'city_name_en': 'New Damietta' },
  { 'id': 311, 'number': 311, 'governorate_number': 19, 'city_name_ar': 'رأس البر', 'city_name_en': 'Ras El Bar' },
  { 'id': 312, 'number': 312, 'governorate_number': 19, 'city_name_ar': 'فارسكور', 'city_name_en': 'Faraskour' },
  { 'id': 313, 'number': 313, 'governorate_number': 19, 'city_name_ar': 'الزرقا', 'city_name_en': 'Zarqa' },
  { 'id': 314, 'number': 314, 'governorate_number': 19, 'city_name_ar': 'السرو', 'city_name_en': 'alsaru' },
  { 'id': 315, 'number': 315, 'governorate_number': 19, 'city_name_ar': 'الروضة', 'city_name_en': 'alruwda' },
  { 'id': 316, 'number': 316, 'governorate_number': 19, 'city_name_ar': 'كفر البطيخ', 'city_name_en': 'Kafr El-Batikh' },
  { 'id': 317, 'number': 317, 'governorate_number': 19, 'city_name_ar': 'عزبة البرج', 'city_name_en': 'Azbet Al Burg' },
  { 'id': 318, 'number': 318, 'governorate_number': 19, 'city_name_ar': 'ميت أبو غالب', 'city_name_en': 'Meet Abou Ghalib' },
  { 'id': 319, 'number': 319, 'governorate_number': 19, 'city_name_ar': 'كفر سعد', 'city_name_en': 'Kafr Saad' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////الشرقية
  { 'id': 320, 'number': 320, 'governorate_number': 20, 'city_name_ar': 'الزقازيق', 'city_name_en': 'Zagazig' },
  { 'id': 321, 'number': 321, 'governorate_number': 20, 'city_name_ar': 'منيا القمح', 'city_name_en': 'Minya Al Qamh' },
  { 'id': 322, 'number': 322, 'governorate_number': 20, 'city_name_ar': 'بلبيس', 'city_name_en': 'Belbeis' },
  { 'id': 323, 'number': 323, 'governorate_number': 20, 'city_name_ar': 'مشتول السوق', 'city_name_en': 'Mashtoul El Souq' },
  { 'id': 324, 'number': 324, 'governorate_number': 20, 'city_name_ar': 'القنايات', 'city_name_en': 'Qenaiat' },
  { 'id': 325, 'number': 325, 'governorate_number': 20, 'city_name_ar': 'أبو حماد', 'city_name_en': 'Abu Hammad' },
  { 'id': 326, 'number': 326, 'governorate_number': 20, 'city_name_ar': 'القرين', 'city_name_en': 'El Qurain' },
  { 'id': 327, 'number': 327, 'governorate_number': 20, 'city_name_ar': 'ههيا', 'city_name_en': 'Hehia' },
  { 'id': 328, 'number': 328, 'governorate_number': 20, 'city_name_ar': 'أبو كبير', 'city_name_en': 'Abu Kabir' },
  { 'id': 329, 'number': 329, 'governorate_number': 20, 'city_name_ar': 'فاقوس', 'city_name_en': 'Faccus' },
  { 'id': 330, 'number': 330, 'governorate_number': 20, 'city_name_ar': 'الصالحية الجديدة', 'city_name_en': 'El Salihia El Gednumbera' },
  { 'id': 331, 'number': 331, 'governorate_number': 20, 'city_name_ar': 'الإبراهيمية', 'city_name_en': 'Al Ibrahimiyah' },
  { 'id': 332, 'number': 332, 'governorate_number': 20, 'city_name_ar': 'ديرب نجم', 'city_name_en': 'Deirb Negm' },
  { 'id': 333, 'number': 333, 'governorate_number': 20, 'city_name_ar': 'كفر صقر', 'city_name_en': 'Kafr Saqr' },
  { 'id': 334, 'number': 334, 'governorate_number': 20, 'city_name_ar': 'أولاد صقر', 'city_name_en': 'Awlad Saqr' },
  { 'id': 335, 'number': 335, 'governorate_number': 20, 'city_name_ar': 'الحسينية', 'city_name_en': 'Husseiniya' },
  { 'id': 336, 'number': 336, 'governorate_number': 20, 'city_name_ar': 'صان الحجر القبلية', 'city_name_en': 'san alhajar alqablia' },
  { 'id': 337, 'number': 337, 'governorate_number': 20, 'city_name_ar': 'منشأة أبو عمر', 'city_name_en': 'Manshayat Abu Omar' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////جنوب سيناء
  { 'id': 338, 'number': 338, 'governorate_number': 21, 'city_name_ar': 'الطور', 'city_name_en': 'Al Toor' },
  { 'id': 339, 'number': 339, 'governorate_number': 21, 'city_name_ar': 'شرم الشيخ', 'city_name_en': 'Sharm El-Shaikh' },
  { 'id': 340, 'number': 340, 'governorate_number': 21, 'city_name_ar': 'دهب', 'city_name_en': 'Dahab' },
  { 'id': 341, 'number': 341, 'governorate_number': 21, 'city_name_ar': 'نويبع', 'city_name_en': 'Nuweiba' },
  { 'id': 342, 'number': 342, 'governorate_number': 21, 'city_name_ar': 'طابا', 'city_name_en': 'Taba' },
  { 'id': 343, 'number': 343, 'governorate_number': 21, 'city_name_ar': 'سانت كاترين', 'city_name_en': 'Saint Catherine' },
  { 'id': 344, 'number': 344, 'governorate_number': 21, 'city_name_ar': 'أبو رديس', 'city_name_en': 'Abu Redis' },
  { 'id': 345, 'number': 345, 'governorate_number': 21, 'city_name_ar': 'أبو زنيمة', 'city_name_en': 'Abu Zenaima' },
  { 'id': 346, 'number': 346, 'governorate_number': 21, 'city_name_ar': 'رأس سدر', 'city_name_en': 'Ras Snumberr' },
  //Done
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////كفر الشيخ
  { 'id': 347, 'number': 347, 'governorate_number': 22, 'city_name_ar': 'كفر الشيخ', 'city_name_en': 'Kafr El Sheikh' },
  { 'id': 348, 'number': 348, 'governorate_number': 22, 'city_name_ar': 'وسط البلد كفر الشيخ', 'city_name_en': 'Kafr El Sheikh Downtown' },
  { 'id': 349, 'number': 349, 'governorate_number': 22, 'city_name_ar': 'دسوق', 'city_name_en': 'Desouq' },
  { 'id': 350, 'number': 350, 'governorate_number': 22, 'city_name_ar': 'فوه', 'city_name_en': 'Fooh' },
  { 'id': 351, 'number': 351, 'governorate_number': 22, 'city_name_ar': 'مطوبس', 'city_name_en': 'Metobas' },
  { 'id': 352, 'number': 352, 'governorate_number': 22, 'city_name_ar': 'برج البرلس', 'city_name_en': 'Burg Al Burullus' },
  { 'id': 353, 'number': 353, 'governorate_number': 22, 'city_name_ar': 'بلطيم', 'city_name_en': 'Baltim' },
  { 'id': 354, 'number': 354, 'governorate_number': 22, 'city_name_ar': 'مصيف بلطيم', 'city_name_en': 'Masief Baltim' },
  { 'id': 355, 'number': 355, 'governorate_number': 22, 'city_name_ar': 'الحامول', 'city_name_en': 'Hamol' },
  { 'id': 356, 'number': 356, 'governorate_number': 22, 'city_name_ar': 'بيلا', 'city_name_en': 'Bella' },
  { 'id': 357, 'number': 357, 'governorate_number': 22, 'city_name_ar': 'الرياض', 'city_name_en': 'Riyadh' },
  { 'id': 358, 'number': 358, 'governorate_number': 22, 'city_name_ar': 'سيدي سالم', 'city_name_en': 'Snumberi Salm' },
  { 'id': 359, 'number': 359, 'governorate_number': 22, 'city_name_ar': 'قلين', 'city_name_en': 'Qellen' },
  { 'id': 360, 'number': 360, 'governorate_number': 22, 'city_name_ar': 'سيدي غازي', 'city_name_en': 'Snumberi Ghazi' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////مطروح
  { 'id': 361, 'number': 361, 'governorate_number': 23, 'city_name_ar': 'مرسى مطروح', 'city_name_en': 'Marsa Matrouh' },
  { 'id': 362, 'number': 362, 'governorate_number': 23, 'city_name_ar': 'الحمام', 'city_name_en': 'El Hamam' },
  { 'id': 363, 'number': 363, 'governorate_number': 23, 'city_name_ar': 'العلمين', 'city_name_en': 'Alamein' },
  { 'id': 364, 'number': 364, 'governorate_number': 23, 'city_name_ar': 'الضبعة', 'city_name_en': 'Dabaa' },
  { 'id': 365, 'number': 365, 'governorate_number': 23, 'city_name_ar': 'النجيلة', 'city_name_en': 'Al-Nagila' },
  { 'id': 366, 'number': 366, 'governorate_number': 23, 'city_name_ar': 'سيدي براني', 'city_name_en': 'Snumberi Brani' },
  { 'id': 367, 'number': 367, 'governorate_number': 23, 'city_name_ar': 'السلوم', 'city_name_en': 'Salloum' },
  { 'id': 368, 'number': 368, 'governorate_number': 23, 'city_name_ar': 'سيوة', 'city_name_en': 'Siwa' },
  { 'id': 369, 'number': 369, 'governorate_number': 23, 'city_name_ar': 'راس الحكمة', 'city_name_en': 'Ras El Hikma' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////الأقصر
  { 'id': 370, 'number': 370, 'governorate_number': 24, 'city_name_ar': 'الأقصر', 'city_name_en': 'Luxor' },
  { 'id': 371, 'number': 371, 'governorate_number': 24, 'city_name_ar': 'الأقصر الجديدة', 'city_name_en': 'New Luxor' },
  { 'id': 372, 'number': 372, 'governorate_number': 24, 'city_name_ar': 'إسنا', 'city_name_en': 'Esna' },
  { 'id': 373, 'number': 373, 'governorate_number': 24, 'city_name_ar': 'طيبة الجديدة', 'city_name_en': 'New Tiba' },
  { 'id': 374, 'number': 374, 'governorate_number': 24, 'city_name_ar': 'الزينية', 'city_name_en': 'Al ziynia' },
  { 'id': 375, 'number': 375, 'governorate_number': 24, 'city_name_ar': 'البياضية', 'city_name_en': 'Al Bayadieh' },
  { 'id': 376, 'number': 376, 'governorate_number': 24, 'city_name_ar': 'القرنة', 'city_name_en': 'Al Qarna' },
  { 'id': 377, 'number': 377, 'governorate_number': 24, 'city_name_ar': 'أرمنت', 'city_name_en': 'Armant' },
  { 'id': 378, 'number': 378, 'governorate_number': 24, 'city_name_ar': 'الطود', 'city_name_en': 'Al Tud' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////قنا
  { 'id': 379, 'number': 379, 'governorate_number': 25, 'city_name_ar': 'قنا', 'city_name_en': 'Qena' },
  { 'id': 380, 'number': 380, 'governorate_number': 25, 'city_name_ar': 'قنا الجديدة', 'city_name_en': 'New Qena' },
  { 'id': 381, 'number': 381, 'governorate_number': 25, 'city_name_ar': 'ابو طشت', 'city_name_en': 'Abu Tesht' },
  { 'id': 382, 'number': 382, 'governorate_number': 25, 'city_name_ar': 'نجع حمادي', 'city_name_en': 'Nag Hammadi' },
  { 'id': 383, 'number': 383, 'governorate_number': 25, 'city_name_ar': 'دشنا', 'city_name_en': 'Deshna' },
  { 'id': 384, 'number': 384, 'governorate_number': 25, 'city_name_ar': 'الوقف', 'city_name_en': 'Alwaqf' },
  { 'id': 385, 'number': 385, 'governorate_number': 25, 'city_name_ar': 'قفط', 'city_name_en': 'Qaft' },
  { 'id': 386, 'number': 386, 'governorate_number': 25, 'city_name_ar': 'نقادة', 'city_name_en': 'Naqada' },
  { 'id': 387, 'number': 387, 'governorate_number': 25, 'city_name_ar': 'فرشوط', 'city_name_en': 'Farshout' },
  { 'id': 388, 'number': 388, 'governorate_number': 25, 'city_name_ar': 'قوص', 'city_name_en': 'Quos' },
  /////////////////////STOP
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////شمال سيناء
  { 'id': 389, 'number': 389, 'governorate_number': 26, 'city_name_ar': 'العريش', 'city_name_en': 'Arish' },
  { 'id': 390, 'number': 390, 'governorate_number': 26, 'city_name_ar': 'الشيخ زويد', 'city_name_en': 'Sheikh Zowanumber' },
  { 'id': 391, 'number': 391, 'governorate_number': 26, 'city_name_ar': 'نخل', 'city_name_en': 'Nakhl' },
  { 'id': 392, 'number': 392, 'governorate_number': 26, 'city_name_ar': 'رفح', 'city_name_en': 'Rafah' },
  { 'id': 393, 'number': 393, 'governorate_number': 26, 'city_name_ar': 'بئر العبد', 'city_name_en': 'Bir al-Abed' },
  { 'id': 394, 'number': 394, 'governorate_number': 26, 'city_name_ar': 'الحسنة', 'city_name_en': 'Al Hasana' },
  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////سوهاج
  { 'id': 395, 'number': 395, 'governorate_number': 27, 'city_name_ar': 'سوهاج', 'city_name_en': 'Sohag' },
  { 'id': 396, 'number': 396, 'governorate_number': 27, 'city_name_ar': 'سوهاج الجديدة', 'city_name_en': 'Sohag El Gednumbera' },
  { 'id': 397, 'number': 397, 'governorate_number': 27, 'city_name_ar': 'أخميم', 'city_name_en': 'Akhmeem' },
  { 'id': 398, 'number': 398, 'governorate_number': 27, 'city_name_ar': 'أخميم الجديدة', 'city_name_en': 'Akhmim El Gednumbera' },
  { 'id': 399, 'number': 399, 'governorate_number': 27, 'city_name_ar': 'البلينا', 'city_name_en': 'Albalina' },
  { 'id': 400, 'number': 400, 'governorate_number': 27, 'city_name_ar': 'المراغة', 'city_name_en': 'El Maragha' },
  { 'id': 401, 'number': 401, 'governorate_number': 27, 'city_name_ar': 'المنشأة', 'city_name_en': 'almunsha\'a' },
  { 'id': 402, 'number': 402, 'governorate_number': 27, 'city_name_ar': 'دار السلام', 'city_name_en': 'Dar AISalaam' },
  { 'id': 403, 'number': 403, 'governorate_number': 27, 'city_name_ar': 'جرجا', 'city_name_en': 'Gerga' },
  { 'id': 404, 'number': 404, 'governorate_number': 27, 'city_name_ar': 'جهينة الغربية', 'city_name_en': 'Jahina Al Gharbia' },
  { 'id': 405, 'number': 405, 'governorate_number': 27, 'city_name_ar': 'ساقلته', 'city_name_en': 'Saqilatuh' },
  { 'id': 406, 'number': 406, 'governorate_number': 27, 'city_name_ar': 'طما', 'city_name_en': 'Tama' },
  { 'id': 407, 'number': 407, 'governorate_number': 27, 'city_name_ar': 'طهطا', 'city_name_en': 'Tahta' },
  { 'id': 408, 'number': 408, 'governorate_number': 27, 'city_name_ar': 'الكوثر', 'city_name_en': 'Alkawthar' },
]

export const newCairo: string[] = [
  "65bbb3541f38895ebe287769",
  "65bbb3541f38895ebe287770",
  "65bbb3541f38895ebe287771",
  "65bbb3541f38895ebe287772",
  "65bbb3541f38895ebe287773",
  "654f711a03e10a7763474c78",
  "63efb3766472f4aa487a56e9"
];
