version: "3.8"
services:
  postgres:
   image: postgres:17
  container_name: postgres_container
  ports:
      - "5432:5432"
  environment:
    POSTGRES_USER: doc-station
    POSTGRES_PASSWORD: doc-station2026
    POSTGRES_DB: doc_station
  volumes:
    - postgres_data:/var/lib/postgresql/data
  restart: always

volumes:
  postgres_data:
