name: Check Project Status

on:
  push:
    branches: 
      - "**"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies & devDependencies
        run: npm install -f

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL:  ${{ secrets.DATABASE_URL }}

      - name: Run TypeScript build
        run: npm run build
